# Copyright (c) 2014 Rohan Chandra
# SPDX-License-Identifier: MIT
# The Jekyl theme "Type" used and modified under the above licence from https://github.com/rohanchandra/type-theme
#
# SITE CONFIGURATION
url: "0.0.0.0" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Hyperledger Sawtooth
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "An enterprise-grade solution for distributed ledgers." # used by search engines
  site_navigation_sort: order

  # Header and footer text
  header_text: >
     <h1>Sawtooth</h1>
  header_text_feature_image: ../examples/img/hero-bg.jpg
  footer_text: >
    <p style="font-size: 1.5em;">
      Hyperledger Sawtooth
    </p>
    <p>
      <a href="/" title="Home"><span class="links">Home</span></a>
      &bull;
      <a href="/about/" title="About Sawtooth"><span class="links">About</span></a>
      &bull;
      <a href="/release/" title="Releases"><span class="links">Releases</span></a>
      &bull;
      <a href="/docs/" title="Documentation"><span class="links">Docs</span></a>
      &bull;
      <a href="/faq/" title="FAQ"><span class="links">FAQ</span></a>
      &bull;
      <a href="/community/" title="Community"><span class="links">Community</span></a>
      &bull;
      <a href="/contact/" title="Contact"><span class="links">Contact</span></a>
    </p>
    <p>
      Find us: &nbsp;
      <a href="https://github.com/hyperledger/sawtooth-core/" target="_blank" title="GitHub"><span  class="links">GitHub</span></a>
      &bull;
      <a href="https://chat.hyperledger.org/channel/sawtooth" target="_blank" title="#sawtooth chat channel"">Rocket.Chat</a>
      &bull;
      <a href="https://twitter.com/search?q=%23HyperledgerSawtooth" target="_blank" title="#sawtooth chat channel"">Twitter</a>
    </p>
    <p>
      Examples: &nbsp;
      <a href="/examples/seafood.html" target="_blank" title="Seafood Supply Chain Traceability">Seafood Supply Chain Traceability</a>
      &bull;
      <a href="/examples/bond.html" target="_blank" title="Bond Asset Settlement">Bond Asset Settlement</a>
      &bull;
      <a href="/examples/marketplace.html" target="_blank" title="Marketplace Digital Asset Exchange">Marketplace Digital Asset Exchange</a>
    </p>
    <p>
      Linux Foundation: &nbsp;
      <a href="http://www.linuxfoundation.org/privacy" target="_blank" title="Privacy Policy">Privacy Policy</a>
      &bull;
      <a href="http://www.linuxfoundation.org/terms" target="_blank" title="Terms of Service">Terms of Service</a>
    </p>
    <p>
      <small class="copyright">Copyright &copy; 2015-2019 contributors to Hyperledger Sawtooth</small>
    </p>
  permalink: /:categories/:year/:month/:day/:release/:title/
  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: hyperledger/sawtooth-core
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: \%23HyperledgerSawtooth
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

# PAGINATION
# paginate: 5
# paginate_path: "info/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true

# BUILD SETTINGS
markdown: kramdown
sass:
  sass_dir: _sass
  style: :compressed
keep_files: [./*]
source: ./source
