# Copyright (c) 2018-2019 Bitwise IO, Inc.
# Licensed under Creative Commons Attribution 4.0 International License
# https://creativecommons.org/licenses/by/4.0/
version: "3.7"

services:
  sawtooth-docs-jekyll:
    build:
      dockerfile: docker/jekyll.dockerfile
      context: .
    image: sawtooth-docs-jekyll
    container_name: sawtooth-docs-jekyll
    working_dir: /srv/jekyll/
    ports:
      - 4000:4000
    volumes:
      - $PWD:/srv/jekyll
    environment:
      - JEKYLL_ENV=${JEKYLL_ENV}
    entrypoint:  |
      bash -c "
        rm -rf  _site
        jekyll serve --config ./_config.yml
      "
