# This configuration file is used by the `make_templated_docs` script to
# determine which files to generate.
#
# Add target files to generate to the `targets` property, with a `template`
# property specifying the template to use, and any `args` to pass to the
# template.
# -----------------------------------------------------------------------------

targets:
